#!/usr/bin/env python3

"""
Mac-friendly electrostatics helper.

This script:
1. Converts cleaned PDB files into PQR files using pdb2pqr.
2. Generates APBS input files.
3. Edits APBS input settings.
4. Runs APBS.
5. Writes electrostatic potential .dx files into atompot/.

Expected folder structure:

protein_dir/
    fix/
        protein_0.pdb
        protein_1.pdb
        ...
    pqr_files/
        protein_0.pqr
        protein_0.in
        ...
    atompot/
        protein_0.dx
        ...

Typical use from another script:

    from calc_electrostatics import pqr_file_generation, apbs_simulation_standard

    pqr_files = pqr_file_generation(dirname="1abc_3mers", inpath="fix")
    apbs_simulation_standard(pqr_files, dirname="1abc_3mers")

Mac notes:
- Uses tools from PATH by default: "pdb2pqr" and "apbs".
- If needed, pass explicit paths:
    pathtopdb2pqr="/Library/Frameworks/Python.framework/Versions/3.10/bin/pdb2pqr"
    apbspath="/opt/anaconda3/envs/myenv/bin/apbs"
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Iterable, List, Sequence


def _resolve_executable(executable: str) -> str:
    """
    Resolve an executable path safely.

    Accepts either:
    - a command available on PATH, e.g. "pdb2pqr"
    - an absolute path
    - a path using "~"
    """
    expanded = os.path.expanduser(executable)

    if os.path.isabs(expanded) or "/" in expanded:
        path = Path(expanded)
        if not path.exists():
            raise FileNotFoundError(f"Executable not found: {path}")
        if not os.access(path, os.X_OK):
            raise PermissionError(f"Executable is not executable: {path}")
        return str(path)

    found = shutil.which(expanded)
    if found is None:
        raise FileNotFoundError(
            f"Could not find executable '{executable}' on PATH. "
            f"Run `which {executable}` to check your environment."
        )

    return found


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _remove_logs(directory: Path) -> None:
    """
    Remove log files generated by pdb2pqr/APBS if present.
    """
    for log_file in directory.glob("*.log"):
        try:
            log_file.unlink()
        except OSError:
            pass


def _stem_without_suffix(path: Path) -> str:
    return path.name[: -len(path.suffix)] if path.suffix else path.name


def pqr_file_generation(
    dirname: str,
    inpath: str,
    pathtopdb2pqr: str = "pdb2pqr",
    forcefield: str = "CHARMM",
) -> List[str]:
    """
    Generate .pqr and .in files from .pdb files.

    Parameters
    ----------
    dirname:
        Parent protein output directory.

        Example:
            "1abc_3mers"

    inpath:
        Subdirectory inside dirname containing .pdb files.

        Example:
            "fix"

    pathtopdb2pqr:
        Path to pdb2pqr executable, or simply "pdb2pqr" if it is on PATH.

    forcefield:
        pdb2pqr force field. Default is "CHARMM".

    Returns
    -------
    List[str]
        List of generated .pqr filenames, not full paths.

        Example:
            ["1abc_0.pqr", "1abc_1.pqr"]
    """
    pdb2pqr = _resolve_executable(pathtopdb2pqr)

    base_dir = Path(os.path.expanduser(dirname)).resolve()
    pdb_dir = base_dir / inpath
    pqr_dir = base_dir / "pqr_files"

    if not pdb_dir.exists():
        raise FileNotFoundError(f"PDB input directory does not exist: {pdb_dir}")

    _ensure_dir(pqr_dir)

    pdb_files = sorted(p for p in pdb_dir.iterdir() if p.is_file() and p.suffix == ".pdb")

    if not pdb_files:
        print(f"[WARN] No .pdb files found in {pdb_dir}")
        return []

    generated_pqr_files: List[str] = []

    for pdb_file in pdb_files:
        key = _stem_without_suffix(pdb_file)
        out_pqr = pqr_dir / f"{key}.pqr"
        out_in = pqr_dir / f"{key}.in"

        cmd = [
            pdb2pqr,
            "--ff",
            forcefield,
            str(pdb_file),
            "--log-level",
            "CRITICAL",
            str(out_pqr),
            "--apbs-input",
            str(out_in),
            "--nodebump",
            "--noopt",
        ]

        print(f"[pdb2pqr] {pdb_file.name} -> {out_pqr.name}")

        try:
            subprocess.run(
                cmd,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"[ERROR] pdb2pqr failed for {pdb_file}")
            print(f"Command: {' '.join(cmd)}")
            if exc.stdout:
                print("--- stdout ---")
                print(exc.stdout)
            if exc.stderr:
                print("--- stderr ---")
                print(exc.stderr)
            continue

        if out_pqr.exists() and out_in.exists():
            generated_pqr_files.append(out_pqr.name)
        else:
            print(f"[WARN] Expected output missing for {pdb_file.name}")

    _remove_logs(pqr_dir)

    if not generated_pqr_files:
        print(f"[WARN] pqr_file_generation returned empty for {base_dir}")

    return generated_pqr_files


def _patch_apbs_input(in_file: Path, dx_relative_path: str) -> None:
    """
    Patch APBS .in file so that:
    - grid dimensions are smaller and standardized
    - output .dx file goes into ../atompot/
    """
    lines = in_file.read_text().splitlines()
    patched_lines: List[str] = []

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("dime "):
            patched_lines.append("    dime 33 33 33")
        elif stripped.startswith("cglen "):
            patched_lines.append("    cglen 15 15 15")
        elif stripped.startswith("fglen "):
            patched_lines.append("    fglen 15 15 15")
        elif stripped.startswith("write pot dx "):
            patched_lines.append(f"    write pot dx {dx_relative_path}")
        else:
            patched_lines.append(line)

    in_file.write_text("\n".join(patched_lines) + "\n")


def apbs_simulation_standard(
    lis: Sequence[str] | Iterable[str],
    dirname: str,
    apbspath: str = "apbs",
) -> List[str]:
    """
    Run APBS on generated .in files.

    Parameters
    ----------
    lis:
        List of generated PQR filenames or input filenames.

        Accepts:
            ["protein_0.pqr", "protein_1.pqr"]

        or:
            ["protein_0.in", "protein_1.in"]

    dirname:
        Parent protein output directory.

    apbspath:
        Path to APBS executable, or simply "apbs" if it is on PATH.

    Returns
    -------
    List[str]
        List of generated .dx file paths.
    """
    apbs = _resolve_executable(apbspath)

    base_dir = Path(os.path.expanduser(dirname)).resolve()
    pqr_dir = base_dir / "pqr_files"
    atompot_dir = base_dir / "atompot"

    if not pqr_dir.exists():
        raise FileNotFoundError(f"PQR directory does not exist: {pqr_dir}")

    _ensure_dir(atompot_dir)

    files = list(lis)

    if not files:
        print(f"[WARN] Empty input list passed to apbs_simulation_standard for {base_dir}")
        return []

    generated_dx_files: List[str] = []

    for item in files:
        item_path = Path(item)
        key = _stem_without_suffix(item_path)

        in_file = pqr_dir / f"{key}.in"
        dx_relative_path = f"../atompot/{key}.dx"
        dx_file = atompot_dir / f"{key}.dx"

        if not in_file.exists():
            print(f"[WARN] Missing APBS input file: {in_file}")
            continue

        _patch_apbs_input(in_file, dx_relative_path)

        cmd = [apbs, str(in_file.name)]

        print(f"[apbs] {in_file.name} -> {dx_file.name}")

        try:
            subprocess.run(
                cmd,
                check=True,
                cwd=str(pqr_dir),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"[ERROR] APBS failed for {in_file}")
            print(f"Command: {' '.join(cmd)}")
            if exc.stdout:
                print("--- stdout ---")
                print(exc.stdout)
            if exc.stderr:
                print("--- stderr ---")
                print(exc.stderr)
            continue

        if dx_file.exists():
            generated_dx_files.append(str(dx_file))
        else:
            print(f"[WARN] APBS completed but expected .dx file was not found: {dx_file}")

    _remove_logs(pqr_dir)

    if not generated_dx_files:
        print(f"[WARN] apbs_simulation_standard generated no .dx files for {base_dir}")

    return generated_dx_files


def run_full_electrostatics(
    dirname: str,
    inpath: str = "fix",
    pathtopdb2pqr: str = "pdb2pqr",
    apbspath: str = "apbs",
    forcefield: str = "CHARMM",
) -> List[str]:
    """
    Convenience wrapper:
    1. Generate PQR/APBS input files.
    2. Run APBS.
    3. Return generated .dx files.
    """
    pqr_files = pqr_file_generation(
        dirname=dirname,
        inpath=inpath,
        pathtopdb2pqr=pathtopdb2pqr,
        forcefield=forcefield,
    )

    dx_files = apbs_simulation_standard(
        lis=pqr_files,
        dirname=dirname,
        apbspath=apbspath,
    )

    return dx_files


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate PQR files and APBS electrostatic .dx files from cleaned PDB files."
    )

    parser.add_argument(
        "--dirname",
        required=True,
        help="Parent protein directory, e.g. 1abc_3mers",
    )

    parser.add_argument(
        "--inpath",
        default="fix",
        help="Subdirectory inside dirname containing .pdb files. Default: fix",
    )

    parser.add_argument(
        "--pdb2pqr",
        default="pdb2pqr",
        help="Path to pdb2pqr executable, or command name if on PATH. Default: pdb2pqr",
    )

    parser.add_argument(
        "--apbs",
        default="apbs",
        help="Path to APBS executable, or command name if on PATH. Default: apbs",
    )

    parser.add_argument(
        "--ff",
        default="CHARMM",
        help="pdb2pqr force field. Default: CHARMM",
    )

    args = parser.parse_args()

    outputs = run_full_electrostatics(
        dirname=args.dirname,
        inpath=args.inpath,
        pathtopdb2pqr=args.pdb2pqr,
        apbspath=args.apbs,
        forcefield=args.ff,
    )

    print(f"[DONE] Generated {len(outputs)} .dx files")
